import { beforeEach, expect, it, vi } from "vitest";
import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { ContinueListening, SyncStatus } from "./SharedState";
import { emptyState, type LocalState } from "./store";
import { Api } from "../api";
import { resolveConflict, state, syncError, syncInFlight, synchronize } from "./client";
import { prefetch } from "./downloads";
import { signInAndSync } from "./signIn";
import type { EpisodeDetail } from "../types";
const player = vi.hoisted(() => ({current:null as {id:number}|null,playEpisode:vi.fn()}));
vi.mock("../player", () => ({ usePlayer: () => player }));
vi.mock("./client", async original => ({ ...await original<typeof import("./client")>(), offlineEnabled:()=>true,state:vi.fn(),syncError:vi.fn(),synchronize:vi.fn(),resolveConflict:vi.fn(),syncInFlight:vi.fn(()=>false) }));
vi.mock("./downloads", () => ({ prefetch: vi.fn() }));
vi.mock("./signIn", () => ({ signInAndSync: vi.fn() }));
let local:LocalState;
const episode={id:1,title:"Shared episode",position_secs:90,played_at:null,downloaded:true} as EpisodeDetail;
beforeEach(() => {
  window.location.hash = "";
  local=emptyState();
  local.snapshot={version:1,cursor:0,replace:true,shows:[],episodes:[episode],settings:{last_listened:1},versions:{}};
  vi.mocked(state).mockImplementation(async()=>structuredClone(local));
  vi.mocked(syncError).mockReturnValue(null);
  vi.mocked(syncInFlight).mockReset().mockReturnValue(false);
  vi.mocked(synchronize).mockReset().mockResolvedValue();
  vi.mocked(resolveConflict).mockReset().mockResolvedValue();
  vi.mocked(prefetch).mockReset().mockResolvedValue();
  vi.mocked(signInAndSync).mockReset();
  sessionStorage.clear();
  vi.spyOn(Api,"episode").mockResolvedValue(episode);
  player.current=null; player.playEpisode.mockReset();
});
it("offers the last shared episode and refreshes its position after a sync", async()=>{
  render(<ContinueListening/>);
  expect(await screen.findByText("Shared episode · 1:30")).toBeInTheDocument();
  fireEvent.click(screen.getByRole("button",{name:"Resume"}));
  expect(player.playEpisode).toHaveBeenCalledWith(episode,"recent");
  vi.mocked(Api.episode).mockResolvedValue({...episode,position_secs:20,downloaded:false});
  window.dispatchEvent(new Event("pods-offline-changed"));
  expect(await screen.findByText("Shared episode · 0:20")).toBeInTheDocument();
  expect(screen.queryByRole("button",{name:"Resume"})).not.toBeInTheDocument();
  expect(screen.getByText(/Keep Pods open/)).toBeInTheDocument();
  vi.mocked(Api.episode).mockResolvedValue({...episode,played_at:10});
  window.dispatchEvent(new Event("pods-offline-changed"));
  await waitFor(()=>expect(screen.queryByText("Continue listening")).not.toBeInTheDocument());
});
it("distinguishes queued changes, conflicts, and the last successful sync", async()=>{
  render(<SyncStatus/>);
  expect(await screen.findByRole("status")).toHaveTextContent("This device has not synchronized with the Mac");
  expect(screen.getByRole("button", { name: "Sync now" })).toBeInTheDocument();
  local.outbox=[{id:"1",sequence:1,entity:"1",field:"played",value:true,base_revision:0}];
  window.dispatchEvent(new Event("pods-offline-changed"));
  await waitFor(()=>expect(screen.getByRole("status")).toHaveTextContent("Changes on this device are waiting to sync"));
  local.outbox[0].conflict=4;
  window.dispatchEvent(new Event("pods-offline-changed"));
  await waitFor(()=>expect(screen.getByRole("status")).toHaveTextContent("both changed Shared episode"));
  expect(screen.getByRole("button", { name: /Keep this device.s change/ })).toBeInTheDocument();
  expect(screen.getByRole("button", { name: "Use the shared change" })).toBeInTheDocument();
  local.outbox=[];local.lastSync=123;
  window.dispatchEvent(new Event("pods-offline-changed"));
  await waitFor(()=>expect(screen.queryByRole("status")).not.toBeInTheDocument());
  vi.mocked(syncError).mockReturnValue("Mac unavailable");
  window.dispatchEvent(new Event("pods-offline-changed"));
  await waitFor(()=>expect(screen.getByRole("status")).toHaveTextContent("The Mac is not reachable"));
  expect(screen.getByRole("button", { name: "Try again" })).toBeInTheDocument();
});
it("does not flash Sync now while a played change is already syncing", async()=>{
  local.lastSync=123;
  local.outbox=[{id:"1",sequence:1,entity:"1",field:"played",value:true,base_revision:0}];
  vi.mocked(syncInFlight).mockReturnValue(true);
  render(<SyncStatus/>);
  await act(async () => { await vi.mocked(state).mock.results[0]?.value; });
  expect(screen.queryByRole("status")).not.toBeInTheDocument();
  expect(screen.queryByRole("button", { name: "Sync now" })).not.toBeInTheDocument();
  vi.mocked(syncInFlight).mockReturnValue(false);
  local.outbox=[];
  window.dispatchEvent(new Event("pods-offline-changed"));
  await act(async () => { await vi.mocked(state).mock.results.at(-1)?.value; });
  expect(screen.queryByRole("button", { name: "Sync now" })).not.toBeInTheDocument();
});
it("keeps this device's change or the shared one, and retries or discards a rejected change", async()=>{
  local.outbox=[{id:"1",sequence:1,entity:"1",field:"played",value:true,base_revision:0,conflict:4}];
  render(<SyncStatus/>);
  fireEvent.click(await screen.findByRole("button", { name: /Keep this device.s change/ }));
  await waitFor(()=>expect(resolveConflict).toHaveBeenCalledWith("1", true));
  await waitFor(()=>expect(screen.getByRole("button", { name: "Use the shared change" })).toBeEnabled());
  fireEvent.click(screen.getByRole("button", { name: "Use the shared change" }));
  await waitFor(()=>expect(resolveConflict).toHaveBeenCalledWith("1", false));
  local.outbox=[{id:"2",sequence:2,entity:"1",field:"played",value:true,base_revision:0,error:"That episode is gone."}];
  window.dispatchEvent(new Event("pods-offline-changed"));
  expect(await screen.findByRole("status")).toHaveTextContent("That episode is gone.");
  await waitFor(()=>expect(screen.getByRole("button", { name: "Try again" })).toBeEnabled());
  fireEvent.click(screen.getByRole("button", { name: "Try again" }));
  await waitFor(()=>expect(resolveConflict).toHaveBeenCalledWith("2", true));
  await waitFor(()=>expect(screen.getByRole("button", { name: "Discard this change" })).toBeEnabled());
  fireEvent.click(screen.getByRole("button", { name: "Discard this change" }));
  await waitFor(()=>expect(resolveConflict).toHaveBeenCalledWith("2", false));
  expect(prefetch).toHaveBeenCalled();
});
it("dismisses an offline notice until a later sync succeeds", async()=>{
  local.lastSync=50;
  vi.mocked(syncError).mockReturnValue("Mac unavailable");
  render(<SyncStatus/>);
  expect(await screen.findByRole("status")).toHaveTextContent("not reachable");
  fireEvent.click(screen.getByRole("button",{name:"Dismiss"}));
  await waitFor(()=>expect(screen.queryByRole("status")).not.toBeInTheDocument());
  window.dispatchEvent(new Event("pods-offline-changed"));
  expect(screen.queryByRole("status")).not.toBeInTheDocument();
  vi.mocked(syncError).mockReturnValue(null);
  local.lastSync=60;
  window.dispatchEvent(new Event("pods-offline-changed"));
  await waitFor(()=>expect(sessionStorage.getItem("pods-sync-notice")).toBeNull());
  vi.mocked(syncError).mockReturnValue("Mac unavailable");
  window.dispatchEvent(new Event("pods-offline-changed"));
  expect(await screen.findByRole("status")).toHaveTextContent("not reachable");
});
it("asks for the passkey when the Mac needs a sign-in and reports a failed attempt", async()=>{
  vi.mocked(syncError).mockReturnValue("Sign in when the Mac is available to synchronize.");
  let finish: () => void = () => {};
  vi.mocked(signInAndSync).mockReturnValue(new Promise(resolve => { finish = () => resolve(); }));
  render(<SyncStatus/>);
  fireEvent.click(await screen.findByRole("button",{name:"Continue with passkey"}));
  expect(await screen.findByRole("button",{name:"Signing in…"})).toBeDisabled();
  finish();
  await waitFor(()=>expect(signInAndSync).toHaveBeenCalled());
  await waitFor(()=>expect(screen.getByRole("button",{name:"Continue with passkey"})).toBeEnabled());
  vi.mocked(signInAndSync).mockRejectedValue(new Error("Passkey sign-in failed"));
  fireEvent.click(screen.getByRole("button",{name:"Continue with passkey"}));
  expect(await screen.findByRole("alert")).toHaveTextContent("Passkey sign-in failed");
});
