import { beforeEach, expect, it, vi } from "vitest";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { ContinueListening, SyncStatus } from "./SharedState";
import { emptyState, type LocalState } from "./store";
import { Api } from "../api";
import { state, syncError } from "./client";
import type { EpisodeDetail } from "../types";
const player = vi.hoisted(() => ({current:null as {id:number}|null,playEpisode:vi.fn()}));
vi.mock("../player", () => ({ usePlayer: () => player }));
vi.mock("./client", async original => ({ ...await original<typeof import("./client")>(), offlineEnabled:()=>true,state:vi.fn(),syncError:vi.fn() }));
let local:LocalState;
const episode={id:1,title:"Shared episode",position_secs:90,played_at:null,downloaded:true} as EpisodeDetail;
beforeEach(() => {
  local=emptyState();
  local.snapshot={version:1,cursor:0,replace:true,shows:[],episodes:[episode],settings:{last_listened:1},versions:{}};
  vi.mocked(state).mockImplementation(async()=>structuredClone(local));
  vi.mocked(syncError).mockReturnValue(null);
  vi.spyOn(Api,"episode").mockResolvedValue(episode);
  player.current=null; player.playEpisode.mockReset();
});
it("offers the last shared episode and refreshes its position after a sync", async()=>{
  render(<ContinueListening/>);
  expect(await screen.findByText("Shared episode · 1:30")).toBeInTheDocument();
  fireEvent.click(screen.getByRole("button",{name:"Resume"}));
  expect(player.playEpisode).toHaveBeenCalledWith(episode,"recent");
  vi.mocked(Api.episode).mockResolvedValue({...episode,position_secs:20,downloaded:false});
  window.dispatchEvent(new Event("pods-offline-changed"));
  expect(await screen.findByText("Shared episode · 0:20")).toBeInTheDocument();
  expect(screen.queryByRole("button",{name:"Resume"})).not.toBeInTheDocument();
  expect(screen.getByText(/Keep Pods open/)).toBeInTheDocument();
  vi.mocked(Api.episode).mockResolvedValue({...episode,played_at:10});
  window.dispatchEvent(new Event("pods-offline-changed"));
  await waitFor(()=>expect(screen.queryByText("Continue listening")).not.toBeInTheDocument());
});
it("distinguishes queued changes, conflicts, and the last successful sync", async()=>{
  render(<SyncStatus/>);
  expect(await screen.findByRole("status")).toHaveTextContent("Not synchronized yet");
  local.outbox=[{id:"1",sequence:1,entity:"1",field:"played",value:true,base_revision:0}];
  window.dispatchEvent(new Event("pods-offline-changed"));
  await waitFor(()=>expect(screen.getByRole("status")).toHaveTextContent("Changes waiting to sync"));
  local.outbox[0].conflict=4;
  window.dispatchEvent(new Event("pods-offline-changed"));
  await waitFor(()=>expect(screen.getByRole("status")).toHaveTextContent("Sync needs attention"));
  local.outbox=[];local.lastSync=123;
  window.dispatchEvent(new Event("pods-offline-changed"));
  await waitFor(()=>expect(screen.getByRole("status")).toHaveTextContent("Synced"));
  vi.mocked(syncError).mockReturnValue("Mac unavailable");
  window.dispatchEvent(new Event("pods-offline-changed"));
  await waitFor(()=>expect(screen.getByRole("status")).toHaveTextContent("Mac unavailable"));
});
